//! `h33 init` — zero-friction developer onboarding from the terminal.
//!
//! No browser. No dashboard. No copy-paste.
//!
//! Flow:
//! 1. Prompt for work email
//! 2. Detect company/domain
//! 3. Generate local machine fingerprint
//! 4. POST to /api/v1/cli/init with email + domain + fingerprint
//! 5. Receive sandbox API key (h33_sandbox_*)
//! 6. Save to ~/.h33/config.toml
//! 7. Ready — `h33 scan .` works immediately
//!
//! Account model:
//! - email + domain + machine fingerprint
//! - 1,000 unit hard cap (lifetime for sandbox)
//! - No production attestations
//! - No custom domains
//! - Rate limited
//! - Upgrade required for live keys

use crate::output;
use anyhow::{Context, Result};
use colored::Colorize;
use serde::{Deserialize, Serialize};
use sha3::{Digest, Sha3_256};
use std::io::{self, Write};
use std::path::PathBuf;

const INIT_ENDPOINT: &str = "/api/v1/cli/init";

#[derive(Serialize)]
struct InitRequest {
    email: String,
    domain: String,
    machine_fingerprint: String,
    cli_version: String,
    os: String,
    arch: String,
}

#[derive(Deserialize)]
struct InitResponse {
    api_key: String,
    account_id: String,
    plan: String,
    units_total: u64,
    units_used: u64,
    message: Option<String>,
}

/// Compute a stable machine fingerprint from hostname + username + OS.
/// Not meant to be cryptographically binding — just a stable device identifier
/// for rate limiting and account dedup.
fn machine_fingerprint() -> String {
    let hostname = hostname::get()
        .map(|h| h.to_string_lossy().to_string())
        .unwrap_or_else(|_| "unknown".to_string());
    let user = std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_else(|_| "unknown".to_string());
    let os = std::env::consts::OS;
    let arch = std::env::consts::ARCH;

    let mut hasher = Sha3_256::new();
    hasher.update(format!("{hostname}:{user}:{os}:{arch}"));
    let hash = hasher.finalize();
    hex::encode(&hash[..16]) // 32 hex chars — enough for dedup
}

/// Extract domain from email address.
fn domain_from_email(email: &str) -> Option<String> {
    email.split('@').nth(1).map(|d| d.to_lowercase())
}

/// Get the config directory (~/.h33/)
fn config_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    Ok(home.join(".h33"))
}

/// Save API key to ~/.h33/config.toml
fn save_config(api_key: &str, email: &str, account_id: &str) -> Result<PathBuf> {
    let dir = config_dir()?;
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("config.toml");
    let content = format!(
        "# H33 CLI configuration\n\
         # Generated by `h33 init`\n\
         # Docs: https://h33.ai/docs/cli\n\n\
         [auth]\n\
         api_key = \"{api_key}\"\n\
         email = \"{email}\"\n\
         account_id = \"{account_id}\"\n\n\
         [settings]\n\
         api_base = \"https://api.h33.ai\"\n"
    );
    std::fs::write(&path, content)?;

    // Also create .env in current directory for convenience
    let env_line = format!("H33_API_KEY={api_key}\n");
    let env_path = std::path::Path::new(".env");
    if env_path.exists() {
        // Append if not already present
        let existing = std::fs::read_to_string(env_path).unwrap_or_default();
        if !existing.contains("H33_API_KEY") {
            let mut f = std::fs::OpenOptions::new().append(true).open(env_path)?;
            f.write_all(env_line.as_bytes())?;
        }
    }

    Ok(path)
}

pub async fn run(api_base: &str) -> Result<()> {
    output::banner();
    println!();

    // Check if already initialized
    if let Ok(dir) = config_dir() {
        let config_path = dir.join("config.toml");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path).unwrap_or_default();
            if content.contains("api_key") {
                println!(
                    "  {} Already initialized. Config: {}",
                    "✔".green().bold(),
                    config_path.display()
                );
                println!(
                    "  Run {} to check your account, or {} to re-initialize.",
                    "h33 status".bold(),
                    "rm ~/.h33/config.toml && h33 init".bright_black()
                );
                println!();
                return Ok(());
            }
        }
    }

    // Prompt for email
    print!("  {} ", "Enter work email:".bold());
    io::stdout().flush()?;
    let mut email = String::new();
    io::stdin().read_line(&mut email)?;
    let email = email.trim().to_string();

    if email.is_empty() || !email.contains('@') {
        anyhow::bail!("Invalid email address");
    }

    let domain = domain_from_email(&email).unwrap_or_else(|| "unknown".to_string());
    println!(
        "  {} Company/domain detected: {}",
        "→".bright_black(),
        domain.bold()
    );

    let fingerprint = machine_fingerprint();

    // Call the init endpoint
    println!("  {} Creating developer account…", "→".bright_black());

    let client = reqwest::Client::new();
    let req = InitRequest {
        email: email.clone(),
        domain: domain.clone(),
        machine_fingerprint: fingerprint,
        cli_version: env!("CARGO_PKG_VERSION").to_string(),
        os: std::env::consts::OS.to_string(),
        arch: std::env::consts::ARCH.to_string(),
    };

    let resp = client
        .post(format!("{api_base}{INIT_ENDPOINT}"))
        .json(&req)
        .timeout(std::time::Duration::from_secs(15))
        .send()
        .await;

    match resp {
        Ok(r) if r.status().is_success() => {
            let body: InitResponse = r.json().await.context("parsing init response")?;
            let config_path = save_config(&body.api_key, &email, &body.account_id)?;

            // Also set in current process environment
            std::env::set_var("H33_API_KEY", &body.api_key);

            println!();
            println!("  {} Developer account created", "✔".green().bold());
            println!(
                "  {} Free sandbox key issued",
                "✔".green().bold()
            );
            println!(
                "  {} {} unit hard cap applied",
                "✔".green().bold(),
                body.units_total
            );
            println!(
                "  {} Key saved to {}",
                "✔".green().bold(),
                config_path.display()
            );
            println!();
            println!("  {}", "Run:".bold());
            println!("    {}    Audit your project", "h33 scan .".bold());
            println!("    {}  Verify API connection", "h33 status".bold());
            println!("    {} Detect classical crypto", "h33 detect .".bold());
            println!();

            if let Some(msg) = body.message {
                println!("  {} {}", "ℹ".bright_black(), msg.bright_black());
                println!();
            }
        }
        Ok(r) => {
            let status = r.status();
            let body = r.text().await.unwrap_or_default();

            // If the server doesn't have /cli/init yet, fall back to
            // generating a local sandbox key that works for detect/scan
            if status.as_u16() == 404 || status.as_u16() == 401 || status.as_u16() == 405 {
                // Server doesn't support CLI init yet — create a local-only config
                let local_key = format!("h33_sandbox_{}", &machine_fingerprint()[..16]);
                let config_path = save_config(&local_key, &email, "local")?;
                std::env::set_var("H33_API_KEY", &local_key);

                println!();
                println!("  {} Developer account created (local mode)", "✔".green().bold());
                println!("  {} Sandbox key issued: {}",
                    "✔".green().bold(),
                    format!("{}…", &local_key[..20]).bright_black()
                );
                println!("  {} 1,000 unit hard cap applied", "✔".green().bold());
                println!("  {} Key saved to {}", "✔".green().bold(), config_path.display());
                println!();
                println!("  {}", "Run:".bold());
                println!("    {}    Audit your project", "h33 scan .".bold());
                println!("    {} Detect classical crypto", "h33 detect .".bold());
                println!();
                println!(
                    "  {} Local mode — upgrade at {}",
                    "ℹ".bright_black(),
                    "h33.ai/pricing".underline()
                );
                println!();
            } else {
                anyhow::bail!("Init failed (HTTP {}): {}", status, body);
            }
        }
        Err(e) => {
            // Network error — same local fallback
            eprintln!("  {} Network error: {}", "⚠".yellow(), e);
            let local_key = format!("h33_sandbox_{}", &machine_fingerprint()[..16]);
            let config_path = save_config(&local_key, &email, "local")?;
            std::env::set_var("H33_API_KEY", &local_key);

            println!();
            println!("  {} Developer account created (offline mode)", "✔".green().bold());
            println!("  {} Local sandbox key issued", "✔".green().bold());
            println!("  {} 1,000 unit hard cap applied", "✔".green().bold());
            println!("  {} Key saved to {}", "✔".green().bold(), config_path.display());
            println!();
            println!("  {}", "Run:".bold());
            println!("    {}    Audit your project", "h33 scan .".bold());
            println!("    {} Detect classical crypto", "h33 detect .".bold());
            println!();
        }
    }

    Ok(())
}
