//! `h33 init` — zero-friction developer onboarding from the terminal.
//!
//! No browser. No dashboard. No copy-paste.
//!
//! Flow:
//! 1. POST /api/h33/keys/sandbox (authenticated via existing session or email flow)
//! 2. If no sandbox key exists → creates one, saves to ~/.h33/config.toml
//! 3. If sandbox key exists → prints masked metadata + rotate/revoke commands
//! 4. `h33 init --rotate` → rotates existing sandbox key, saves new one
//! 5. `h33 init --revoke` → revokes sandbox key, removes local config
//!
//! Account model:
//! - Sandbox keys: exactly 1 per user, 1,000 unit hard cap
//! - No ZK middleware required
//! - Sandbox keys do NOT count against live key tier limits
//! - Never prints the full key except on fresh create/rotate

use crate::client::join_url;
use crate::config;
use crate::output;
use anyhow::{Context, Result};
use colored::Colorize;
use serde::{Deserialize, Serialize};
use sha3::{Digest, Sha3_256};
use std::path::PathBuf;

const SANDBOX_ENDPOINT: &str = "/api/h33/keys/sandbox";

#[derive(Serialize)]
struct SandboxRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    action: Option<String>,
}

/// Postgres BIGINT comes as string through Node.js JSON — handle both.
fn deserialize_string_or_u64<'de, D>(deserializer: D) -> Result<Option<u64>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::de;
    struct StringOrU64Visitor;
    impl<'de> de::Visitor<'de> for StringOrU64Visitor {
        type Value = Option<u64>;
        fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.write_str("a u64 or string representing a u64")
        }
        fn visit_u64<E: de::Error>(self, v: u64) -> Result<Self::Value, E> { Ok(Some(v)) }
        fn visit_i64<E: de::Error>(self, v: i64) -> Result<Self::Value, E> { Ok(Some(v as u64)) }
        fn visit_str<E: de::Error>(self, v: &str) -> Result<Self::Value, E> {
            v.parse::<u64>().map(Some).map_err(de::Error::custom)
        }
        fn visit_none<E: de::Error>(self) -> Result<Self::Value, E> { Ok(None) }
        fn visit_unit<E: de::Error>(self) -> Result<Self::Value, E> { Ok(None) }
    }
    deserializer.deserialize_any(StringOrU64Visitor)
}

/// Response when a new sandbox key is created or rotated.
#[derive(Deserialize)]
#[allow(dead_code)]
struct SandboxKeyResponse {
    success: bool,
    #[serde(default)]
    action: Option<String>,
    #[serde(default)]
    exists: Option<bool>,
    #[serde(default)]
    key: Option<String>,
    #[serde(default)]
    key_prefix: Option<String>,
    #[serde(default)]
    id: Option<String>,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    environment: Option<String>,
    #[serde(default)]
    unit_cap: Option<u64>,
    #[serde(default, deserialize_with = "deserialize_string_or_u64")]
    units_used: Option<u64>,
    #[serde(default)]
    status: Option<String>,
    #[serde(default)]
    last_used_at: Option<String>,
    #[serde(default)]
    created_at: Option<String>,
    #[serde(default)]
    message: Option<String>,
    #[serde(default)]
    warning: Option<String>,
}

/// Compute a stable machine fingerprint from hostname + username + OS.
fn machine_fingerprint() -> String {
    let hostname = hostname::get()
        .map(|h| h.to_string_lossy().to_string())
        .unwrap_or_else(|_| "unknown".to_string());
    let user = std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_else(|_| "unknown".to_string());
    let os = std::env::consts::OS;
    let arch = std::env::consts::ARCH;

    let mut hasher = Sha3_256::new();
    hasher.update(format!("{hostname}:{user}:{os}:{arch}"));
    let hash = hasher.finalize();
    hex::encode(&hash[..16])
}

/// Get the config directory (~/.h33/)
fn config_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    Ok(home.join(".h33"))
}

/// Save API key to ~/.h33/config.toml
fn save_config(api_key: &str, account_id: &str) -> Result<PathBuf> {
    let dir = config_dir()?;
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("config.toml");
    let content = format!(
        "# H33 CLI configuration\n\
         # Generated by `h33 init`\n\
         # Docs: https://h33.ai/docs/cli\n\n\
         [auth]\n\
         api_key = \"{api_key}\"\n\
         account_id = \"{account_id}\"\n\
         environment = \"sandbox\"\n\n\
         [settings]\n\
         api_base = \"https://api.h33.ai\"\n\
         auth_base = \"https://h33.ai\"\n"
    );
    std::fs::write(&path, content)?;
    Ok(path)
}

/// Remove API key from ~/.h33/config.toml (on revoke)
fn remove_config() -> Result<()> {
    let dir = config_dir()?;
    let path = dir.join("config.toml");
    if path.exists() {
        std::fs::remove_file(&path)?;
    }
    // Also clean .env if we wrote to it
    let env_path = std::path::Path::new(".env");
    if env_path.exists() {
        let content = std::fs::read_to_string(env_path).unwrap_or_default();
        let cleaned: Vec<&str> = content
            .lines()
            .filter(|l| !l.starts_with("H33_API_KEY"))
            .collect();
        std::fs::write(env_path, cleaned.join("\n") + "\n")?;
    }
    Ok(())
}

/// Build the HTTP client with auth token from config if available.
fn build_client_with_auth() -> Result<(reqwest::Client, Option<String>)> {
    let client = reqwest::Client::builder()
        .user_agent(concat!("h33-cli/", env!("CARGO_PKG_VERSION")))
        .timeout(std::time::Duration::from_secs(15))
        .no_proxy()
        .build()
        .context("building HTTP client")?;
    let token = config::api_key();
    Ok((client, token))
}

/// Mask a key prefix: show first 12 chars + dots
fn mask_key(prefix: &str) -> String {
    if prefix.len() >= 12 {
        format!("{}••••••••••••", prefix)
    } else {
        format!("{}••••••••", prefix)
    }
}

/// Create a local-only offline config, clearly marked as non-API.
fn create_offline_config() -> Result<()> {
    let dir = config_dir()?;
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("config.toml");
    let fp = &machine_fingerprint()[..16];
    let content = format!(
        "# H33 CLI configuration — OFFLINE / TEST MODE ONLY\n\
         # This key does NOT authenticate against the H33 API.\n\
         # Run `h33 init` when online to get a real sandbox key.\n\n\
         [auth]\n\
         api_key = \"h33_offline_{fp}\"\n\
         account_id = \"offline\"\n\
         environment = \"offline\"\n\n\
         [settings]\n\
         api_base = \"https://api.h33.ai\"\n\
         offline = true\n"
    );
    std::fs::write(&path, content)?;

    println!();
    println!(
        "  {} Offline test config created.",
        "⚠".yellow().bold()
    );
    println!(
        "  {} This key will NOT work for API calls.",
        "⚠".yellow().bold()
    );
    println!(
        "  {} Saved to {}",
        "→".bright_black(),
        path.display()
    );
    println!(
        "  {} {} and {} will run locally only.",
        "→".bright_black(),
        "h33 detect".bold(),
        "h33 scan".bold()
    );
    println!(
        "  Run {} when online to get a real sandbox key.",
        "h33 init".bold()
    );
    println!();
    Ok(())
}

/// `h33 init` — create or show existing sandbox key
pub async fn run(api_base: &str, rotate: bool, revoke: bool, offline: bool) -> Result<()> {
    output::banner();
    println!();

    // Sandbox keys are managed through Auth1 directly.
    // The Netlify proxy at h33.ai blocks non-browser clients (WAF/Botshield).
    let auth_base = if api_base == "https://api.h33.ai" || api_base == "https://h33.ai" {
        "https://auth-api.z101.ai"
    } else {
        api_base
    };

    // Determine action
    let action = if rotate {
        Some("rotate".to_string())
    } else if revoke {
        Some("revoke".to_string())
    } else {
        None
    };

    // We need auth to call the sandbox endpoint.
    // Try existing config first, then fall back to email login flow.
    let (client, existing_token) = build_client_with_auth()?;

    let token = match existing_token {
        Some(t) => t,
        None => {
            // No existing key — need to authenticate first
            // For now, guide the user to log in via dashboard then retry
            println!(
                "  {} No authentication found.",
                "⚠".yellow().bold()
            );
            println!(
                "  Run {} first to authenticate, then run {} again.",
                "h33 signup".bold(),
                "h33 init".bold()
            );
            println!(
                "  Or set {} in your environment.",
                "H33_API_KEY".bold()
            );
            println!();
            return Ok(());
        }
    };

    let body = SandboxRequest { action: action.clone() };

    let url = join_url(auth_base, SANDBOX_ENDPOINT);
    let resp = client
        .post(&url)
        .header("Authorization", format!("Bearer {token}"))
        .json(&body)
        .timeout(std::time::Duration::from_secs(15))
        .send()
        .await;

    match resp {
        Ok(r) if r.status().is_success() => {
            let data: SandboxKeyResponse =
                r.json().await.context("parsing sandbox key response")?;

            // ── REVOKE ──
            if revoke {
                remove_config()?;
                println!(
                    "  {} Sandbox key revoked.",
                    "✔".green().bold()
                );
                println!(
                    "  {} Local config removed.",
                    "✔".green().bold()
                );
                println!(
                    "  Run {} to create a new sandbox key.",
                    "h33 init".bold()
                );
                println!();
                return Ok(());
            }

            // ── EXISTING KEY (no action requested) ──
            if data.exists.unwrap_or(false) && !rotate {
                let prefix = data.key_prefix.as_deref().unwrap_or("h33_sand_****");
                let cap = data.unit_cap.unwrap_or(1_000);
                let used = data.units_used.unwrap_or(0);
                let created = data.created_at.as_deref().unwrap_or("unknown");

                println!(
                    "  {} Existing sandbox key found.",
                    "ℹ".bright_black().bold()
                );
                println!();
                println!("  Key:      {}", mask_key(prefix).bright_black());
                println!("  Units:    {} / {} used", used, cap);
                println!("  Created:  {}", created);
                println!(
                    "  Status:   {}",
                    data.status
                        .as_deref()
                        .unwrap_or("active")
                        .green()
                );
                println!();
                println!("  {}", "Use it, rotate it, or revoke it.".bold());
                println!();
                println!("    {}    Rotate to a new key", "h33 init --rotate".bold());
                println!("    {}   Revoke and remove", "h33 init --revoke".bold());
                println!();
                return Ok(());
            }

            // ── NEW KEY or ROTATED KEY ──
            let full_key = data.key.as_deref().unwrap_or("");
            if full_key.is_empty() {
                anyhow::bail!("Server returned success but no key");
            }

            let account_id = data.id.as_deref().unwrap_or("sandbox");
            let config_path = save_config(full_key, account_id)?;
            std::env::set_var("H33_API_KEY", full_key);

            let verb = if rotate { "rotated" } else { "created" };
            let cap = data.unit_cap.unwrap_or(1_000);

            println!();
            println!(
                "  {} Sandbox key {}.",
                "✔".green().bold(),
                verb
            );
            println!(
                "  {} {} unit hard cap applied.",
                "✔".green().bold(),
                cap.to_string().bold()
            );
            println!(
                "  {} Key saved to {}",
                "✔".green().bold(),
                config_path.display()
            );
            println!();

            if let Some(w) = &data.warning {
                println!(
                    "  {} {}",
                    "⚠".yellow(),
                    w.yellow()
                );
                println!();
            }

            println!("  {}", "Run:".bold());
            println!("    {}    Audit your project", "h33 scan .".bold());
            println!("    {}  Verify API connection", "h33 status".bold());
            println!("    {} Detect classical crypto", "h33 detect .".bold());
            println!();
        }
        Ok(r) if r.status().as_u16() == 404 => {
            if offline {
                create_offline_config()?;
            } else {
                println!();
                println!(
                    "  {} Server does not support terminal sandbox init yet.",
                    "✗".red().bold()
                );
                println!(
                    "  Get your API key from the dashboard at {}",
                    "h33.ai/dashboard".bold().underline()
                );
                println!(
                    "  Then run: {}",
                    "export H33_API_KEY=h33_live_...".bright_black()
                );
                println!();
            }
        }
        Ok(r) if r.status().as_u16() == 401 || r.status().as_u16() == 403 => {
            // Auth rejected — key is revoked, expired, or invalid
            println!();
            println!(
                "  {} Authentication failed. Your saved key may be revoked or expired.",
                "✗".red().bold()
            );
            println!();
            println!("  To fix:");
            println!(
                "    1. Log in at {} and copy your API key",
                "h33.ai/dashboard".bold().underline()
            );
            println!(
                "    2. Run: {}",
                "export H33_API_KEY=<your-key>".bright_black()
            );
            println!(
                "    3. Run: {}",
                "h33 init".bold()
            );
            println!();
            println!(
                "  Or remove the stale config: {}",
                "rm ~/.h33/config.toml".bright_black()
            );
            println!();
        }
        Ok(r) => {
            let status = r.status();
            let body = r.text().await.unwrap_or_default();
            anyhow::bail!("Sandbox key request failed (HTTP {}): {}", status, body);
        }
        Err(e) => {
            if offline {
                eprintln!(
                    "  {} Could not reach H33 API: {}",
                    "⚠".yellow(),
                    e
                );
                create_offline_config()?;
            } else {
                println!();
                println!(
                    "  {} Could not reach H33 API.",
                    "✗".red().bold()
                );
                println!(
                    "  {} {}",
                    "Error:".bright_black(),
                    format!("{e}").bright_black()
                );
                println!();
                println!(
                    "  Check your network connection and try again, or use {} for local-only test mode.",
                    "h33 init --offline".bold()
                );
                println!();
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_machine_fingerprint_stable() {
        let a = machine_fingerprint();
        let b = machine_fingerprint();
        assert_eq!(a, b);
        assert_eq!(a.len(), 32);
    }

    #[test]
    fn test_mask_key() {
        assert_eq!(mask_key("h33_sand_a1b2"), "h33_sand_a1b2••••••••••••");
        assert_eq!(mask_key("short"), "short••••••••");
    }

    #[test]
    fn test_config_dir() {
        let dir = config_dir().unwrap();
        assert!(dir.to_string_lossy().contains(".h33"));
    }

    #[test]
    fn test_save_and_remove_config() {
        // Use a temp dir to avoid touching real config
        let tmp = std::env::temp_dir().join("h33_test_init");
        std::fs::create_dir_all(&tmp).unwrap();
        let config_path = tmp.join("config.toml");

        let content = format!(
            "[auth]\napi_key = \"h33_sand_test1234567890ab\"\naccount_id = \"test\"\nenvironment = \"sandbox\"\n"
        );
        std::fs::write(&config_path, &content).unwrap();
        assert!(config_path.exists());

        // Verify content
        let read = std::fs::read_to_string(&config_path).unwrap();
        assert!(read.contains("h33_sand_test1234567890ab"));
        assert!(read.contains("sandbox"));

        // Cleanup
        std::fs::remove_dir_all(&tmp).unwrap();
    }

    #[test]
    fn test_sandbox_request_no_action() {
        let req = SandboxRequest { action: None };
        let json = serde_json::to_string(&req).unwrap();
        assert_eq!(json, "{}");
    }

    #[test]
    fn test_sandbox_request_rotate() {
        let req = SandboxRequest {
            action: Some("rotate".to_string()),
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("\"action\":\"rotate\""));
    }

    #[test]
    fn test_sandbox_request_revoke() {
        let req = SandboxRequest {
            action: Some("revoke".to_string()),
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("\"action\":\"revoke\""));
    }

    #[test]
    fn test_sandbox_response_existing_key() {
        let json = r#"{
            "success": true,
            "exists": true,
            "key_prefix": "h33_sand_a1b2",
            "unit_cap": 1000,
            "units_used": 42,
            "status": "active",
            "message": "Existing sandbox key found."
        }"#;
        let resp: SandboxKeyResponse = serde_json::from_str(json).unwrap();
        assert!(resp.success);
        assert_eq!(resp.exists, Some(true));
        assert!(resp.key.is_none()); // No full key exposed for existing
        assert_eq!(resp.unit_cap, Some(1000));
        assert_eq!(resp.units_used, Some(42));
    }

    #[test]
    fn test_sandbox_response_new_key() {
        let json = r#"{
            "success": true,
            "action": "created",
            "key": "h33_sand_abcdef1234567890abcdef1234567890abcdef12345678",
            "key_prefix": "h33_sand_abc",
            "id": "uuid-here",
            "unit_cap": 1000,
            "warning": "Save this key now — it will not be shown again."
        }"#;
        let resp: SandboxKeyResponse = serde_json::from_str(json).unwrap();
        assert!(resp.success);
        assert!(resp.key.is_some()); // Full key only on create
        assert_eq!(resp.action, Some("created".to_string()));
    }

    #[test]
    fn test_existing_key_never_exposes_full_key() {
        // When exists=true and no action, the response must NOT contain the full key
        let json = r#"{
            "success": true,
            "exists": true,
            "key_prefix": "h33_sand_a1b2",
            "unit_cap": 1000,
            "units_used": 0,
            "status": "active"
        }"#;
        let resp: SandboxKeyResponse = serde_json::from_str(json).unwrap();
        assert!(resp.key.is_none(), "Existing key must never expose full key");
    }
}
